on:
  push:
    branches:
    - master

name: Node.js

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: 'Checkout' 
      uses: actions/checkout@master

    - uses: azure/webapps-deploy@v2
      with:
        publish-profile: ${{ secrets.AzurePublishProfile }}

    - name: logout
      run: az logout
